name: Build aria2c

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11.0, macos-12.0, macos-13.0, macos-latest]
        platform: [x86_64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up macOS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          brew install cppunit gettext openssl libssh2 c-ares sqlite3 \
          autoconf automake pkg-config libtool libuv libxml2 zlib upx libuv
          
      - name: Build aria2c
        run: |
          export LDFLAGS="-L/usr/local/opt/libxml2/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite3/lib -L/usr/local/lib -L/usr/local/opt/libuv/lib";
          export CPPFLAGS="-I/usr/local/opt/libxml2/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite3/include -I/usr/local/include -I/usr/local/opt/libuv/include";
          export PKG_CONFIG_PATH="/usr/local/opt/sqlite3/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/opt/libuv/lib/pkgconfig";
          export CC=clang
          export CXX=clang++          
          git clone https://github.com/aria2/aria2.git
          cd aria2
          autoreconf -i
          ./configure \
            --enable-static \
            --with-openssl=/usr/local/opt/openssl \
            --with-libssh2 \
            --with-libcares \
            --with-libexpat \
            --with-libsqlite3 \
            --with-libxml2 \
            --with-zlib \
            --enable-bittorrent \
            --enable-metalink \
            --enable-xml-rpc \
            --enable-websocket \
            --enable-websocket-via-libwebsockets \
            --enable-utf8-only \
            --enable-largefile \
            --enable-async-dns \
            --enable-ftp \
            --enable-sftp \
            --enable-http \
            --enable-segment-allocation \
            --enable-libaria2 \
            --disable-nls \
            ARIA2_STATIC=yes
          make

      - name: Archive artifacts
        run: |
          mkdir -p artifacts/${{ matrix.os }}/$platform
          strip aria2/aria2c
          cp aria2/aria2c artifacts/${{ matrix.os }}/$platform/
        working-directory: .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aria2c
          path: artifacts
