name: Build aria2c

on:
  push:


jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        os: [11, 12, 13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install c-ares openssl expat zlib libssh2 sqlite3
        brew install --cask macfuse
        brew install sshfs

    - name: Build aria2c
      run: |
        ./configure ARIA2_STATIC=yes --with-appletls --with-openssl --with-sqlite3 --with-ssh2 --enable-async-dns --enable-metalink --enable-bittorrent --enable-dht --enable-dht6 --enable-utp --enable-bittorrent --enable-metalink --enable-ftp --enable-sftp --enable-mmap --enable-checksum --enable-aria2c --enable-xml --enable-http2
        make

    - name: Upload to GitHub Releases
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./aria2c
        asset_name: aria2c-${{ matrix.os }}-${{ matrix.arch }}
        asset_content_type: application/octet-stream
