name: Build aria2c

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64]
        os: [12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Install dependencies
      run: |
        brew install cppunit gettext openssl libssh2 c-ares sqlite3 \
        autoconf automake pkg-config libtool libuv libxml2 zlib upx libuv
        
        
    - name: Build c-ares
      run: |
        (cd ..;
        curl -L https://c-ares.haxx.se/download/c-ares-1.17.2.tar.gz -o c-ares.tar.gz;
        tar xf c-ares.tar.gz;
        cd c-ares-*;
        ./configure --disable-shared;
        make -j`sysctl -n machdep.cpu.thread_count`;
        make install -j`sysctl -n machdep.cpu.thread_count`;)
        autoreconf -i;
        export LDFLAGS="-L/usr/local/opt/libxml2/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite3/lib -L/usr/local/lib -L/usr/local/opt/libuv/lib";
        export CPPFLAGS="-I/usr/local/opt/libxml2/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite3/include -I/usr/local/include -I/usr/local/opt/libuv/include";
        export PKG_CONFIG_PATH="/usr/local/opt/sqlite3/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/opt/libuv/lib/pkgconfig";
        export CC=clang
        export CXX=clang++
        sudo rm -fr /usr/local/opt/libxml2/lib/*.dylib /usr/local/opt/libssh2/lib/*.dylib /usr/local/opt/openssl@1.1/lib/*.dylib /usr/local/opt/openssl@1.1/lib/*.dylib \
        /usr/local/opt/c-ares/lib/*.dylib /usr/local/opt/gettext/lib/*.dylib /usr/local/opt/sqlite/lib/*.dylib /usr/local/opt/zlib/lib/*.dylib /usr/local/opt/libuv/lib/*.dylib || true;
        
    - name: Build aria2c
      run: |     
        git clone https://github.com/aria2/aria2.git
        cd aria2
        autoreconf -i
        ./configure \
          --enable-static \
          --with-openssl=/usr/local/opt/openssl \
          --with-libssh2 \
          --with-libcares \
          --with-libexpat \
          --with-libsqlite3 \
          --with-libxml2 \
          --with-zlib \
          --enable-bittorrent \
          --enable-metalink \
          --enable-xml-rpc \
          --enable-websocket \
          --enable-websocket-via-libwebsockets \
          --enable-utf8-only \
          --enable-largefile \
          --enable-async-dns \
          --enable-ftp \
          --enable-sftp \
          --enable-http \
          --enable-segment-allocation \
          --enable-libaria2 \
          --disable-nls \
          --enable-shared=no \
          ARIA2_STATIC=yes
        make -j`sysctl -n machdep.cpu.thread_count`

    - name: Set executable permissions & strip
      run: |     
        chmod a+x src/aria2c
        strip src/aria2c
        mkdir ./artifact/
        mv src/aria2c ./artifact/aria2c

    - name: upload macOS aria2c
      if: ${{ runner.os == 'macOS' && matrix.arch == 'amd64' }}
      uses: actions/upload-artifact@master
      with:
        name: aria2c-macos-${{ matrix.arch }}
        path: ./artifact/